import { mysqlTable, serial, int, varchar } from 'drizzle-orm/mysql-core';

export const eventLiveExplain1617 = mysqlTable('event_live_explain_1617', {
    id: serial('id').primaryKey().autoincrement().notNull(),
    element: int('element').notNull(),
    elementType: int('element_type'),
    teamId: int('team_id'),
    event: int('event').notNull(),
    fixture: varchar('fixture', { length: 255 }),
    totalPoints: int('total_points').notNull(),
    bps: int('bps'),
    bonus: int('bonus'),
    minutes: int('minutes'),
    minutesPoints: int('minutes_points'),
    goalsScored: int('goals_scored'),
    goalsScoredPoints: int('goals_scored_points'),
    assists: int('assists'),
    assistsPoints: int('assists_points'),
    cleanSheets: int('clean_sheets'),
    cleanSheetsPoints: int('clean_sheets_points'),
    goalsConceded: int('goals_conceded'),
    goalsConcededPoints: int('goals_conceded_points'),
    ownGoals: int('own_goals'),
    ownGoalsPoints: int('own_goals_points'),
    penaltiesSaved: int('penalties_saved'),
    penaltiesSavedPoints: int('penalties_saved_points'),
    penaltiesMissed: int('penalties_missed'),
    penaltiesMissedPoints: int('penalties_missed_points'),
    yellowCards: int('yellow_cards'),
    yellowCardsPoints: int('yellow_cards_points'),
    redCards: int('red_cards'),
    redCardsPoints: int('red_cards_points'),
    saves: int('saves'),
    savesPoints: int('saves_points'),
});
