import {
    mysqlTable,
    serial,
    int,
    varchar,
    timestamp,
} from 'drizzle-orm/mysql-core';

export const leagueEventReport = mysqlTable('league_event_report', {
    id: serial('id').primaryKey().autoincrement().notNull(),
    leagueId: int('league_id').notNull(),
    leagueType: varchar('league_type', { length: 255 }).notNull(),
    leagueName: varchar('league_name', { length: 255 }).notNull(),
    entry: int('entry').notNull(),
    entryName: varchar('entry_name', { length: 255 }),
    playerName: varchar('player_name', { length: 255 }),
    overallPoints: int('overall_points'),
    overallRank: int('overall_rank'),
    teamValue: int('team_value'),
    bank: int('bank'),
    event: int('event').notNull(),
    eventPoints: int('event_points'),
    eventTransfers: int('event_transfers'),
    eventTransfersCost: int('event_transfers_cost'),
    eventNetPoints: int('event_net_points'),
    eventBenchPoints: int('event_bench_points'),
    eventAutoSubPoints: int('event_auto_sub_points'),
    eventRank: int('event_rank'),
    eventChip: varchar('event_chip', { length: 255 }),
    position1: int('position1'),
    position2: int('position2'),
    position3: int('position3'),
    position4: int('position4'),
    position5: int('position5'),
    position6: int('position6'),
    position7: int('position7'),
    position8: int('position8'),
    position9: int('position9'),
    position10: int('position10'),
    position11: int('position11'),
    position12: int('position12'),
    position13: int('position13'),
    position14: int('position14'),
    position15: int('position15'),
    captain: int('captain'),
    captainPoints: int('captain_points'),
    captainBlank: int('captain_blank'),
    captainSelected: varchar('captain_selected', { length: 255 }),
    viceCaptain: int('vice_captain'),
    viceCaptainPoints: int('vice_captain_points'),
    viceCaptainBlank: int('vice_captain_blank'),
    viceCaptainSelected: varchar('vice_captain_selected', { length: 255 }),
    playedCaptain: int('played_captain'),
    highestScore: int('highest_score'),
    highestScorePoints: int('highest_score_points'),
    highestScoreBlank: int('highest_score_blank'),
    highestScoreSelected: varchar('highest_score_selected', { length: 255 }),
    updateTime: timestamp('update_time'),
});
