import {
    mysqlTable,
    serial,
    int,
    varchar,
    timestamp,
} from 'drizzle-orm/mysql-core';

export const popularScoutResult = mysqlTable('popular_scout_result', {
    id: serial('id').primaryKey().autoincrement().notNull(),
    event: int('event').notNull(),
    source: varchar('source', { length: 255 }),
    position1: int('position_1'),
    position1Points: int('position_1_points'),
    position2: int('position_2'),
    position2Points: int('position_2_points'),
    position3: int('position_3'),
    position3Points: int('position_3_points'),
    position4: int('position_4'),
    position4Points: int('position_4_points'),
    position5: int('position_5'),
    position5Points: int('position_5_points'),
    position6: int('position_6'),
    position6Points: int('position_6_points'),
    position7: int('position_7'),
    position7Points: int('position_7_points'),
    position8: int('position_8'),
    position8Points: int('position_8_points'),
    position9: int('position_9'),
    position9Points: int('position_9_points'),
    position10: int('position_10'),
    position10Points: int('position_10_points'),
    position11: int('position_11'),
    position11Points: int('position_11_points'),
    position12: int('position_12'),
    position12Points: int('position_12_points'),
    position13: int('position_13'),
    position13Points: int('position_13_points'),
    position14: int('position_14'),
    position14Points: int('position_14_points'),
    position15: int('position_15'),
    position15Points: int('position_15_points'),
    captain: int('captain'),
    captainPoints: int('captain_points'),
    viceCaptain: int('vice_captain'),
    viceCaptainPoints: int('vice_captain_points'),
    playedCaptain: int('played_captain'),
    playedCaptainPoints: int('played_captain_points'),
    rawTotalPoints: int('raw_total_points'),
    totalPoints: int('total_points'),
    averagePoints: int('average_points'),
    chip: varchar('chip', { length: 255 }),
    updateTime: timestamp('update_time'),
});
