import {
    mysqlTable,
    serial,
    int,
    varchar,
    timestamp,
} from 'drizzle-orm/mysql-core';

export const scout2324 = mysqlTable('scout_2324', {
    id: serial('id').primaryKey().autoincrement().notNull(),
    event: int('event').notNull(),
    entry: int('entry').notNull(),
    scoutName: varchar('scout_name', { length: 255 }),
    transfers: int('transfers'),
    leftTransfers: int('left_transfers'),
    gkp: int('gkp'),
    gkpTeamId: int('gkp_team_id'),
    gkpPoints: int('gkp_points'),
    def: int('def'),
    defTeamId: int('def_team_id'),
    defPoints: int('def_points'),
    mid: int('mid'),
    midTeamId: int('mid_team_id'),
    midPoints: int('mid_points'),
    fwd: int('fwd'),
    fwdTeamId: int('fwd_team_id'),
    fwdPoints: int('fwd_points'),
    captain: int('captain'),
    captainTeamId: int('captain_team_id'),
    captainPoints: int('captain_points'),
    reason: varchar('reason', { length: 255 }),
    eventPoints: int('event_points'),
    totalPoints: int('total_points'),
    updateTime: timestamp('update_time'),
});
