import {
    mysqlTable,
    serial,
    int,
    timestamp,
    decimal,
} from 'drizzle-orm/mysql-core';

export const tournamentKnockout2324 = mysqlTable('tournament_knockout_2324', {
    id: serial('id').primaryKey().autoincrement().notNull(),
    tournamentId: int('tournament_id').notNull(),
    round: int('round'),
    startGw: int('start_gw'),
    endGw: int('end_gw'),
    matchId: int('match_id'),
    nextMatchId: int('next_match_id'),
    homeEntry: int('home_entry'),
    homeEntryNetPoints: int('home_entry_net_points'),
    homeEntryGoalsScored: int('home_entry_goals_scored'),
    homeEntryGoalsConceded: int('home_entry_goals_conceded'),
    homeEntryWinningNum: decimal('home_entry_winning_num'),
    awayEntry: int('away_entry'),
    awayEntryNetPoints: int('away_entry_net_points'),
    awayEntryGoalsScored: int('away_entry_goals_scored'),
    awayEntryGoalsConceded: int('away_entry_goals_conceded'),
    awayEntryWinningNum: decimal('away_entry_winning_num'),
    roundWinner: int('round_winner'),
    createTime: timestamp('create_time'),
    updateTime: timestamp('update_time'),
});
