import {
    mysqlTable,
    serial,
    int,
    varchar,
    timestamp,
} from 'drizzle-orm/mysql-core';

export const tournamentInfo1920 = mysqlTable('tournament_info_1920', {
    id: serial('id').primaryKey().autoincrement().notNull(),
    name: varchar('name', { length: 255 }).notNull(),
    creator: varchar('creator', { length: 255 }),
    adminerEntry: int('adminer_entry'),
    leagueType: varchar('league_type', { length: 255 }),
    leagueId: int('league_id'),
    totalTeam: int('total_team'),
    tournamentMode: varchar('tournament_mode', { length: 255 }),
    groupMode: varchar('group_mode', { length: 255 }).notNull(),
    teamPerGroup: int('team_per_group'),
    groupNum: int('group_num'),
    groupFillAverage: int('group_fill_average').default(1),
    groupRounds: int('group_rounds'),
    groupPlayAgainstNum: int('group_play_against_num'),
    groupStartGw: int('group_start_gw'),
    groupEndGw: int('group_end_gw'),
    groupQualifiers: int('group_qualifiers'),
    knockoutMode: varchar('knockout_mode', { length: 255 }).notNull(),
    knockoutTeam: int('knockout_team'),
    knockoutRounds: int('knockout_rounds'),
    knockoutEvents: int('knockout_events').default(0),
    knockoutPlayAgainstNum: int('knockout_play_against_num'),
    knockoutStartGw: int('knockout_start_gw'),
    knockoutEndGw: int('knockout_end_gw'),
    state: int('state').default(1),
    createTime: timestamp('create_time'),
    updateTime: timestamp('update_time'),
});
