CREATE TABLE `entry_event_pick` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`event` int NOT NULL,
	`entry` int NOT NULL,
	`transfers` int,
	`transfers_cost` int,
	`chip` varchar(255),
	`picks` varchar(1000),
	`update_time` timestamp,
	CONSTRAINT `entry_event_pick_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `entry_event_result` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`event` int NOT NULL,
	`entry` int NOT NULL,
	`event_points` int,
	`event_transfers` int,
	`event_transfers_cost` int,
	`event_net_points` int,
	`event_bench_points` int,
	`event_auto_sub_points` int,
	`event_rank` int,
	`event_chip` varchar(255),
	`played_captain` int,
	`captain_points` int,
	`event_picks` varchar(255),
	`event_auto_subs` varchar(255),
	`overall_points` int,
	`overall_rank` int,
	`team_value` int,
	`bank` int,
	`update_time` timestamp,
	CONSTRAINT `entry_event_result_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `entry_event_transfers` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`event` int NOT NULL,
	`entry` int NOT NULL,
	`element_in` int,
	`element_in_cost` int,
	`element_in_played` int,
	`element_in_points` int DEFAULT 0,
	`element_out` int,
	`element_out_cost` int,
	`element_out_points` int DEFAULT 0,
	`time` varchar(255),
	CONSTRAINT `entry_event_transfers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `entry_history_info` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`entry` int NOT NULL,
	`season` varchar(255),
	`total_points` int,
	`overall_rank` int,
	`update_time` timestamp,
	CONSTRAINT `entry_history_info_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `entry_info` (
	`entry` serial AUTO_INCREMENT NOT NULL,
	`entry_name` varchar(255),
	`player_name` varchar(255),
	`region` varchar(255),
	`started_event` int,
	`overall_points` int,
	`overall_rank` int,
	`bank` int,
	`team_value` int,
	`total_transfers` int,
	`last_entry_name` varchar(255),
	`last_overall_points` int,
	`last_overall_rank` int,
	`last_team_value` int,
	`used_entry_name` varchar(255),
	`create_time` timestamp,
	`update_time` timestamp,
	CONSTRAINT `entry_info_entry` PRIMARY KEY(`entry`)
);
--> statement-breakpoint
CREATE TABLE `entry_league_info` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`entry` int NOT NULL,
	`league_id` int NOT NULL,
	`type` varchar(255) NOT NULL,
	`league_type` varchar(255) NOT NULL,
	`league_name` varchar(255),
	`entry_rank` int,
	`entry_last_rank` int,
	`start_event` int,
	`created` varchar(255),
	`update_time` timestamp,
	CONSTRAINT `entry_league_info_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `event` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`deadline_time` varchar(255),
	`average_entry_score` int,
	`finished` int NOT NULL,
	`highest_score` int,
	`highest_scoring_entry` int,
	`is_previous` int,
	`is_current` int,
	`is_next` int,
	`most_selected` int,
	`most_transferred_in` int,
	`most_captained` int,
	`most_vice_captained` int,
	CONSTRAINT `event_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `event_fixture` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`code` int NOT NULL,
	`event` int NOT NULL,
	`kickoff_time` timestamp,
	`started` int,
	`finished` int,
	`provisional_start_time` int,
	`finished_provisional` int,
	`minutes` int,
	`team_h` int,
	`team_h_difficulty` int,
	`team_h_score` int,
	`team_a` int,
	`team_a_difficulty` int,
	`team_a_score` int,
	`update_time` timestamp,
	CONSTRAINT `event_fixture_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `event_live` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`element` int NOT NULL,
	`element_type` int,
	`team_id` int,
	`event` int NOT NULL,
	`fixture` varchar(255),
	`minutes` int,
	`goals_scored` int,
	`assists` int,
	`clean_sheets` int,
	`goals_conceded` int,
	`own_goals` int,
	`penalties_saved` int,
	`penalties_missed` int,
	`yellow_cards` int,
	`red_cards` int,
	`saves` int,
	`bonus` int,
	`bps` int,
	`total_points` int DEFAULT 0,
	`mng_win` int,
	`mng_draw` int,
	`mng_loss` int,
	`mng_underdog_win` int,
	`mng_underdog_draw` int,
	`mng_clean_sheets` int,
	`mng_goals_scored` int,
	CONSTRAINT `event_live_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `event_live_explain` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`element` int NOT NULL,
	`element_type` int,
	`team_id` int,
	`event` int NOT NULL,
	`fixture` varchar(255),
	`total_points` int NOT NULL,
	`bps` int,
	`bonus` int,
	`minutes` int,
	`minutes_points` int,
	`goals_scored` int,
	`goals_scored_points` int,
	`assists` int,
	`assists_points` int,
	`clean_sheets` int,
	`clean_sheets_points` int,
	`goals_conceded` int,
	`goals_conceded_points` int,
	`own_goals` int,
	`own_goals_points` int,
	`penalties_saved` int,
	`penalties_saved_points` int,
	`penalties_missed` int,
	`penalties_missed_points` int,
	`yellow_cards` int,
	`yellow_cards_points` int,
	`red_cards` int,
	`red_cards_points` int,
	`saves` int,
	`saves_points` int,
	`mng_win` int,
	`mng_win_points` int,
	`mng_draw` int,
	`mng_draw_points` int,
	`mng_loss` int,
	`mng_loss_points` int,
	`mng_underdog_win` int,
	`mng_underdog_win_points` int,
	`mng_underdog_draw` int,
	`mng_underdog_draw_points` int,
	`mng_clean_sheets` int,
	`mng_clean_sheets_points` int,
	`mng_goals_scored` int,
	`mng_goals_scored_points` int,
	CONSTRAINT `event_live_explain_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `event_live_summary` (
	`element` serial AUTO_INCREMENT NOT NULL,
	`element_type` int,
	`team_id` int,
	`minutes` int,
	`goals_scored` int,
	`assists` int,
	`clean_sheets` int,
	`goals_conceded` int,
	`own_goals` int,
	`penalties_saved` int,
	`penalties_missed` int,
	`yellow_cards` int,
	`red_cards` int,
	`saves` int,
	`bonus` int,
	`bps` int,
	`total_points` int DEFAULT 0,
	`update_time` timestamp,
	`mng_win` int,
	`mng_draw` int,
	`mng_loss` int,
	`mng_underdog_win` int,
	`mng_underdog_draw` int,
	`mng_clean_sheets` int,
	`mng_goals_scored` int,
	CONSTRAINT `event_live_summary_element` PRIMARY KEY(`element`)
);
--> statement-breakpoint
CREATE TABLE `league_event_report` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`league_id` int NOT NULL,
	`league_type` varchar(255) NOT NULL,
	`league_name` varchar(255) NOT NULL,
	`entry` int NOT NULL,
	`entry_name` varchar(255),
	`player_name` varchar(255),
	`overall_points` int,
	`overall_rank` int,
	`team_value` int,
	`bank` int,
	`event` int NOT NULL,
	`event_points` int,
	`event_transfers` int,
	`event_transfers_cost` int,
	`event_net_points` int,
	`event_bench_points` int,
	`event_auto_sub_points` int,
	`event_rank` int,
	`event_chip` varchar(255),
	`position1` int,
	`position2` int,
	`position3` int,
	`position4` int,
	`position5` int,
	`position6` int,
	`position7` int,
	`position8` int,
	`position9` int,
	`position10` int,
	`position11` int,
	`position12` int,
	`position13` int,
	`position14` int,
	`position15` int,
	`captain` int,
	`captain_points` int,
	`captain_blank` int,
	`captain_selected` varchar(255),
	`vice_captain` int,
	`vice_captain_points` int,
	`vice_captain_blank` int,
	`vice_captain_selected` varchar(255),
	`played_captain` int,
	`highest_score` int,
	`highest_score_points` int,
	`highest_score_blank` int,
	`highest_score_selected` varchar(255),
	`update_time` timestamp,
	CONSTRAINT `league_event_report_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `player` (
	`element` serial AUTO_INCREMENT NOT NULL,
	`code` int,
	`price` int,
	`start_price` int,
	`element_type` varchar(255) NOT NULL,
	`first_name` varchar(255),
	`second_name` varchar(255),
	`web_name` varchar(255),
	`team_id` int,
	CONSTRAINT `player_element` PRIMARY KEY(`element`)
);
--> statement-breakpoint
CREATE TABLE `player_history` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`code` int NOT NULL,
	`season` varchar(255) NOT NULL,
	`price` int,
	`start_price` int,
	`total_points` int,
	`minutes` int,
	`goals_scored` int,
	`assists` int,
	`clean_sheets` int,
	`goals_conceded` int,
	`own_goals` int,
	`penalties_saved` int,
	`penalties_missed` int,
	`yellow_cards` int,
	`red_cards` int,
	`saves` int,
	`bonus` int,
	`bps` int,
	`influence` varchar(255),
	`creativity` varchar(255),
	`threat` varchar(255),
	`ict_index` varchar(255),
	CONSTRAINT `player_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `player_stat` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`event` int NOT NULL,
	`element` int NOT NULL,
	`code` int,
	`match_played` int,
	`chance_of_playing_next_round` int,
	`chance_of_playing_this_round` int,
	`dreamteam_count` int,
	`event_points` int,
	`form` varchar(255),
	`in_dreamteam` int DEFAULT 0,
	`news` varchar(255),
	`news_added` varchar(255),
	`points_per_game` varchar(255),
	`selected_by_percent` varchar(255),
	`minutes` int,
	`goals_scored` int,
	`assists` int,
	`clean_sheets` int,
	`goals_conceded` int,
	`own_goals` int,
	`penalties_saved` int,
	`penalties_missed` int,
	`yellow_cards` int,
	`red_cards` int,
	`saves` int,
	`bonus` int,
	`bps` int,
	`influence` varchar(255),
	`creativity` varchar(255),
	`threat` varchar(255),
	`ict_index` varchar(255),
	`transfers_in_event` int,
	`transfers_out_event` int,
	`transfers_in` int,
	`transfers_out` int,
	`corners_and_indirect_freekicks_order` int,
	`direct_freekicks_order` int,
	`penalties_order` int,
	`mng_win` int,
	`mng_draw` int,
	`mng_loss` int,
	`mng_underdog_win` int,
	`mng_underdog_draw` int,
	`mng_clean_sheets` int,
	`mng_goals_scored` int,
	`update_time` timestamp,
	CONSTRAINT `player_stat_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `player_summary` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`season` varchar(255) NOT NULL,
	`element` int NOT NULL,
	`web_name` varchar(255),
	`code` int,
	`start_price` int,
	`end_price` int,
	`element_type` int,
	`team_id` int,
	`team_name` varchar(255),
	`team_short_name` varchar(255),
	`minutes` int,
	`goals_scored` int,
	`assists` int,
	`clean_sheets` int,
	`goals_conceded` int,
	`own_goals` int,
	`penalties_saved` int,
	`penalties_missed` int,
	`yellow_cards` int,
	`red_cards` int,
	`saves` int,
	`bonus` int,
	`bps` int,
	`total_points` int DEFAULT 0,
	`mng_win` int,
	`mng_draw` int,
	`mng_loss` int,
	`mng_underdog_win` int,
	`mng_underdog_draw` int,
	`mng_clean_sheets` int,
	`mng_goals_scored` int,
	`update_time` timestamp,
	CONSTRAINT `player_summary_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `player_value` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`element` int NOT NULL,
	`element_type` varchar(255) NOT NULL,
	`event` int,
	`value` int NOT NULL,
	`change_date` varchar(255),
	`change_type` varchar(255),
	`last_value` int,
	`update_time` timestamp,
	CONSTRAINT `player_value_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `standing` (
	`position` serial AUTO_INCREMENT NOT NULL,
	`event` int NOT NULL,
	`team_id` int NOT NULL,
	`team_name` varchar(255),
	`team_short_name` varchar(255),
	`points` int NOT NULL,
	`played` int,
	`won` int,
	`drawn` int,
	`lost` int,
	`goals_for` int,
	`goals_against` int,
	`goals_difference` int,
	`create_time` timestamp,
	CONSTRAINT `standing_position` PRIMARY KEY(`position`)
);
--> statement-breakpoint
CREATE TABLE `team` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`code` int,
	`name` varchar(255),
	`short_name` varchar(255),
	CONSTRAINT `team_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tournament_battle_group_result` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`tournament_id` int NOT NULL,
	`group_id` int NOT NULL,
	`event` int NOT NULL,
	`home_index` int,
	`home_entry` int,
	`home_entry_net_points` int DEFAULT 0,
	`home_entry_rank` int DEFAULT 0,
	`home_entry_match_points` int DEFAULT 0,
	`away_index` int,
	`away_entry` int,
	`away_entry_net_points` int DEFAULT 0,
	`away_entry_rank` int DEFAULT 0,
	`away_entry_match_points` int,
	`update_time` timestamp,
	CONSTRAINT `tournament_battle_group_result_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tournament_entry` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`tournament_id` int NOT NULL,
	`league_id` int,
	`entry` int,
	`create_time` timestamp,
	CONSTRAINT `tournament_entry_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tournament_group` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`tournament_id` int NOT NULL,
	`group_id` int NOT NULL,
	`group_name` varchar(255),
	`group_index` int NOT NULL,
	`entry` int,
	`start_gw` int,
	`end_gw` int,
	`group_points` int DEFAULT 0,
	`group_rank` int,
	`play` int DEFAULT 0,
	`win` int DEFAULT 0,
	`draw` int DEFAULT 0,
	`lose` int DEFAULT 0,
	`total_points` int,
	`total_transfers_cost` int,
	`total_net_points` int,
	`qualified` int DEFAULT 0,
	`overall_rank` int,
	`create_time` timestamp,
	`update_time` timestamp,
	CONSTRAINT `tournament_group_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tournament_info` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`creator` varchar(255),
	`adminer_entry` int,
	`league_id` int,
	`league_type` varchar(255),
	`total_team` int,
	`tournament_mode` varchar(255),
	`group_mode` varchar(255),
	`team_per_group` int,
	`group_num` int,
	`group_start_gw` int,
	`group_end_gw` int,
	`group_fill_average` int DEFAULT 1,
	`group_rounds` int,
	`group_play_against_num` int,
	`group_qualifiers` int,
	`knockout_mode` varchar(255),
	`knockout_team` int,
	`knockout_rounds` int,
	`knockout_events` int,
	`knockout_play_against_num` int,
	`knockout_start_gw` int,
	`knockout_end_gw` int,
	`state` int DEFAULT 1,
	`create_time` timestamp,
	`update_time` timestamp,
	CONSTRAINT `tournament_info_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tournament_knockout` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`tournament_id` int NOT NULL,
	`round` int,
	`start_gw` int,
	`end_gw` int,
	`match_id` int,
	`next_match_id` int,
	`home_entry` int,
	`home_entry_net_points` int,
	`home_entry_goals_scored` int,
	`home_entry_goals_conceded` int,
	`home_entry_winning_num` decimal,
	`away_entry` int,
	`away_entry_net_points` int,
	`away_entry_goals_scored` int,
	`away_entry_goals_conceded` int,
	`away_entry_winning_num` decimal,
	`round_winner` int,
	`create_time` timestamp,
	`update_time` timestamp,
	CONSTRAINT `tournament_knockout_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tournament_knockout_result` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`tournament_id` int NOT NULL,
	`event` int NOT NULL,
	`match_id` int NOT NULL,
	`play_against_id` int NOT NULL,
	`home_entry` int,
	`home_entry_net_points` int,
	`home_entry_rank` int,
	`home_entry_goals_scored` int,
	`home_entry_goals_conceded` int,
	`away_entry` int,
	`away_entry_net_points` int,
	`away_entry_rank` int,
	`away_entry_goals_scored` int,
	`away_entry_goals_conceded` int,
	`match_winner` int,
	`create_time` timestamp,
	`update_time` timestamp,
	CONSTRAINT `tournament_knockout_result_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tournament_points_group_result` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`tournament_id` int NOT NULL,
	`group_id` int NOT NULL,
	`event` int NOT NULL,
	`entry` int NOT NULL,
	`event_group_rank` int,
	`event_points` int,
	`event_cost` int,
	`event_net_points` int,
	`event_rank` int,
	`update_time` timestamp,
	CONSTRAINT `tournament_points_group_result_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tournament_royale` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`tournament_id` int NOT NULL,
	`event` int NOT NULL,
	`event_eliminated_num` int,
	`next_event_eliminated_num` int,
	`event_eliminated_entries` varchar(255),
	`waiting_eliminated_entries` varchar(255),
	`all_eliminated_entries` varchar(255),
	`create_time` timestamp,
	`update_time` timestamp,
	CONSTRAINT `tournament_royale_id` PRIMARY KEY(`id`)
);
