name: Pull Request Check

on:
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Create .env file
              run: |
                  cat << EOF > .env
                  # Database Configuration
                  DB_HOST=${{ secrets.DB_HOST }}
                  DB_PORT=3306
                  DB_USER=${{ secrets.DB_USER }}
                  DB_PASSWORD=${{ secrets.DB_PASSWORD }}
                  DB_NAME=${{ secrets.DB_NAME }}

                  # API Configuration
                  API_PORT=3000

                  # Redis Configuration
                  REDIS_HOST=${{ secrets.REDIS_HOST }}
                  REDIS_PORT=6379
                  REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
                  REDIS_DB=0

                  # Logging Configuration
                  LOG_LEVEL=info
                  EOF

            - name: Install dependencies
              run: bun install

            - name: Run route tests
              run: bun test test/routes/*.test.ts

            - name: Run linter
              run: bun lint

            - name: Type check
              run: bun type-check
